export const GAME_ACTION_TYPES = {
    SET_SHUFFLE_STATUS: 'game/SET_SHUFFLE_STATUS',
    SET_STOLEN_GIFT_TURN_INDEX: 'game/SET_STOLEN_GIFT_TURN_INDEX',
    SET_TURN_INDEX: 'game/SET_TURN_INDEX',
    SET_LAST_GIFT_STOLEN: 'game/SET_LAST_GIFT_STOLEN'
};