export const GAME_ACTION_TYPES = {
    SET_SHUFFLE_STATUS: 'game/SET_SHUFFLE_STATUS',
    SET_STOLEN_GIFT_TURN_INDEX: 'game/SET_STOLEN_GIFT_TURN_INDEX',
    SET_TURN_INDEX: 'game/SET_TURN_INDEX',
    SET_LAST_GIFT_STOLEN: 'game/SET_LAST_GIFT_STOLEN',
    ADD_GAME_HISTORY: 'game/ADD_GAME_HISTORY',
    REMOVE_GAME_HISTORY: 'game/REMOVE_GAME_HISTORY',
    SET_GAME_IS_OVER: 'game/SET_GAME_IS_OVER',
    SET_GAME_IS_STARTED: 'game/SET_GAME_IS_STARTED',
    SET_FIRST_PLAYER_REPLAYED: 'game/SET_FIRST_PLAYER_REPLAYED',
    RESET_GAME_STATE: 'game/RESET_GAME_STATE',
    SET_SYSTEM_NOTIFICATION: 'system/SET_SYSTEM_NOTIFICATION',
    SET_PRESENT_OVERLAY: 'system/SET_PRESENT_OVERLAY'
};