export const PRESENTS_ACTION_TYPES = {
    SWAP_OWNERS: 'presents/SWAP_OWNERS',
    ADD_OWNER_HISTORY: 'presents/ADD_OWNER_HISTORY',
    REMOVE_OWNER_HISTORY: 'presents/REMOVE_OWNER_HISTORY',
    RESET_PRESENTS_STATE: 'presents/RESET_PRESENTS_STATE',
    SET_PRESENTS: 'presents/SET_PRESENTS',
    SET_CARD_IMGS_UPLOADED: 'presents/SET_CARD_IMGS_UPLOADED',
    SHUFFLE_PRESENTS: 'presents/SHUFFLE_PRESENTS'
};