export const PLAYERS_ACTION_TYPES = {
    SHUFFLE_PLAYERS: 'players/SHUFFLE_PLAYERS',
    REMOVE_PRESENT_HISTORY: 'players/REMOVE_PRESENT_HISTORY',
    ADD_PRESENT_HISTORY: 'players/ADD_PRESENT_HISTORY',
    SWAP_PRESENTS: 'players/SWAP_PRESENTS',
    RESET_PLAYERS_STATE: 'players/RESET_PLAYERS_STATE',
    SET_PLAYERS: 'players/SET_PLAYERS'
};